### ISSUE TITLE
[React] alarm (사이드바) 만들기 

### ISSUE THREAD

**Issue by yechoi42** [transcendence42/ft_transcendence#23]
![image](https://user-images.githubusercontent.com/61399588/123567513-4b013480-d7fd-11eb-9f0f-ece11fa76ac0.png)

https://www.figma.com/file/5HxFo9c6v6b7IxhuUXNv1f/ft_transcendence?node-id=0%3A1

**Comment by hochan222** [comment]
- [ ] layout 나누기
- [ ] profile 
- [ ] 알림
- [ ] 친구목록
- [ ] 채팅

**Comment by hochan222** [comment]
<img src="https://user-images.githubusercontent.com/22424891/123896075-d6b0c780-d99b-11eb-92ff-b98beb002b49.png" height="600px"/>
