### ISSUE TITLE
[React] Chat Page 만들기

### ISSUE THREAD

**Issue by hochan222** [transcendence42/ft_transcendence#28]
- [x] layout 나누기
- [x] ( 세부내용 )

**Comment by yhshin0** [comment]
# chat page layout
![image](https://user-images.githubusercontent.com/51621520/123751143-58e4b180-d8f2-11eb-9596-1c6f8284d9b0.png)

**Comment by yhshin0** [comment]
## 세부내용
- [ ] tab을 눌렀을 때 tab에 맞는 테이블 출력
- [ ] 채팅방 삭제
- [ ] 채팅방 생성
- [ ] 페이지네이션
