### ISSUE TITLE
[NestJS] alarm resource 생성

### ISSUE THREAD

**Issue by yhshin0** [transcendence42/ft_transcendence#30]
- [x] docker-compose에서 테스트할 수 있는 환경 만들기
  - [x] start-server, stop-server script 작성
  - [x] 코드 수정 후 그대로 반영되게하기
- [x] nest cli를 사용하여 각 테이블에 해당하는 resource 생성 및 구성(postgresql에 데이터를 CRUD 할 수 있을 정도로)
  - [x] code-first
  - [x] entity 작성
  - [x] create 로직 작성
  - [x] read 로직 작성
  - [x] delete 로직 작성 
  - [x] update 로직 작성
- [x] 간단한 CRUD 테스트

---

- https://www.youtube.com/watch?v=xMP8JQaHS8E
- https://www.youtube.com/watch?v=nDe9R3OHg-4
- https://www.youtube.com/watch?v=nDN4JRbFEns
- chat api
  -  https://github.com/guiquintelas/nestjs-chat-api

**Comment by hochan222** [comment]
```graphql
mutation ($alarm:CreateAlarmInput!){
  createAlarm(createAlarmInput:$alarm) {
    PP_400_userID
    PP_400_title
    PP_400_content
    PP_400_type
    PP_400_link
  }
}
```

```graphql
{
  "alarm": {
    "PP_400_userID": "holee",
    "PP_400_title": "대전",
    "PP_400_content": "하하핳",
    "PP_400_type": "notification",
    "PP_400_link": ""
  }
}
```

**Comment by hochan222** [comment]
![image](https://user-images.githubusercontent.com/22424891/124124709-bd02a380-dab3-11eb-8403-e7481e062327.png)

잘 들어갔다 기분이 너무 죠아
