### ISSUE TITLE
[docker-compose]  ERROR: for db  Cannot start service db: Mounts denied

### ISSUE THREAD

**Issue by hochan222** [transcendence42/ft_transcendence#44]
![image](https://user-images.githubusercontent.com/22424891/123898753-e1219000-d9a0-11eb-992c-386ac4d9997f.png)

실행환경: cluster

```sh
Successfully tagged fttranscendence_front:latest
WARNING: Image for service front was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating db ...
Creating db ... error

ERROR: for db  Cannot start service db: Mounts denied:
The path /goinfre/holee/ft_transcendence/back/database/data/prod
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.

ERROR: for db  Cannot start service db: Mounts denied:
The path /goinfre/holee/ft_transcendence/back/database/data/prod
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.
ERROR: Encountered errors while bringing up the project.
```

**Comment by yechoi42** [comment]
사용한 명령어는 뭔가요?

**Comment by hochan222** [comment]
```sh
docker-compose up -d
```

를 썼고 문제 원인은 docker-compose를 쓸때 지정한 shared folder 이외의 folder는 접근이 금지돼있어서 따로 추가를 시켜주어야합니다. 

저희 코드의 경우

```
./back/database/data/prod:/var/lib/postgresql/data/
```

으로 docker compose가 지정한 공유 폴더가 아니기 때문에 오류가 난 것이고,

```
/tmp/ft_transcendence/back/database/data/prod:/var/lib/postgresql/data/
```
등과같이 경로로를 수정해야합니다.

아래는 공유 폴더 보는법 입니다.

![image](https://user-images.githubusercontent.com/22424891/123900563-3d39e380-d9a4-11eb-8ce4-f85e2555bb2a.png)

https://knight76.tistory.com/entry/docker-mac-%EB%94%94%EB%A0%89%ED%86%A0%EB%A6%AC%EB%A5%BC-docker-container-linux-%EB%94%94%EB%A0%89%ED%86%A0%EB%A6%AC%EB%A1%9C-%EB%B3%B5%EC%82%AC%ED%95%A0-%EB%95%8C-%EC%9C%A0%EC%9D%98%EC%A0%90

**Comment by hochan222** [comment]
저희는 back/front code를 공유해야하니 따로 폴더를 설정해야겠네요..!

**Comment by hochan222** [comment]
저는 이렇게 해결했습니다.

![image](https://user-images.githubusercontent.com/22424891/123901414-d7e6f200-d9a5-11eb-8e6f-b1de17dcbf76.png)
