### ISSUE TITLE
42api OAuth 구현

### ISSUE THREAD

**Issue by hochan222** [transcendence42/ft_transcendence#54]
- [ ] back
- [ ] front

**Comment by yechoi42** [comment]
![Untitled](https://user-images.githubusercontent.com/61399588/124464156-ca2ed380-ddce-11eb-8980-c96e7e198325.png)

🔗 [42API docs](https://api.intra.42.fr/apidoc/guides/web_application_flow)

**Comment by yechoi42** [comment]
- [ ] 0. 42 oauth 서버로 리다이렉션 - front
- [ ] 작성중..

**Comment by yechoi42** [comment]
### 문제 상황

현재 서버에서 유저 인증을 마치면, 클라이언트로 jwt토큰을 쿠키로 보내줍니다. 클라이언트가 받은 response header의 set-cookie 헤더에 토큰이 들어온 게 보입니다.(참고로 브라우저는 파이어폭스입니다.) 그러니까 인증과정부터 토큰 발급, 헤더로 토큰 보내기, 클라이언트가 응답받기까지는 잘 된다는 겁니다.  
<img width="542" alt="Screen Shot 2021-07-09 at 3 55 39 PM" src="https://user-images.githubusercontent.com/61399588/125036809-5fcbab00-e0ce-11eb-8f2e-28e426f33126.png">

문제는 클라이언트에게 쿠키 설정을 하라고 했는데도, 클라이언트는 쿠키를 설정을 하지 않는데 있습니다. 아래 보면 application의 cookie가 텅 빈 게 보이죠. 
![image](https://user-images.githubusercontent.com/61399588/125037111-b89b4380-e0ce-11eb-950f-c4749bcc8774.png)

### CORS 설정
왜 set-cookie 헤더를 받아놓고도, 클라이언트는 쿠키 설정을 못하는 걸까요? 이유는 CORS로 추측합니다.
서버와 클라이언트의 출처는 다릅니다. 현재 개발환경에선 서버는 `http://localhost:5500`, 클라이언트는 `http://localhost:3000`입니다.
리소스의 출처가 다르기 때문에 쿠키를 받고도 셋팅을 못하는 것일 수 있습니다. 

### 지금까지 시도해본 것들
그래서 CORS 설정을 해줍니다. 설정을 해줘도 안된다는 게 문젠데요... 제대로 안해줬기 때문에 그런거겠죠...? 제발... 지금까지 설정해놓은 것들을 공유합니다. 잘못된 것은 빠르게 잡아주시면 감사하겠습니다.

**Comment by yechoi42** [comment]
### CORS 설정
왜 set-cookie 헤더를 받아놓고도, 클라이언트는 쿠키 설정을 못하는 걸까요? 이유는 CORS로 추측합니다. [이 스택오버플로우](https://stackoverflow.com/questions/61555100/cookie-in-set-cookie-header-not-being-set)를 비롯해, reponse의 set-cookie 헤더 값이 왜 설정되지 않느냐고 검색해보면 문제는 공통적으로 CORS로 꼽힙니다. 

서버와 클라이언트의 출처는 다릅니다. 현재 개발환경에선 서버는 `http://localhost:5500`, 클라이언트는 `http://localhost:3000`입니다.리소스의 출처가 다르기 때문에 쿠키를 받고도 셋팅을 못하는 것일 수 있습니다. 

그럼 CORS 설정이 잘 돼있는지, 현재의 설정을 확인해보겠습니다.

#### NestJS에서의 설정
`back/src/app.module.ts` 소스 코드 중 일부입니다. 
```
@Module({
  imports: [
    GraphQLModule.forRoot({
      autoSchemaFile: 'schema.gql',
      installSubscriptionHandlers: true,
      cors: {
        credentials: true,
        origin: 'http://localhost:3000',
      },
    }),
    TypeOrmModule.forRoot(),
    UsersModule,
    AlarmsModule,
    GamesModule,
    ChatsModule,
    ChatLogsModule,
    PubSubModule,
    AuthModule,
    PassportModule.register({ session: true }),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```


🔗 https://docs.nestjs.kr/security/cors

**Comment by hochan222** [comment]
- https://api.intra.42.fr/apidoc/guides/web_application_flow

**Comment by hochan222** [comment]
문제 원인: localhost와 127.0.0.1 을 혼용해서 써서 cors error가 났다. 따라서 set-cookie 가 정상적으로 들어왔음에도 설정이 안됐다.

**Comment by hochan222** [comment]
@yechoi42  알림의 프로필이 안나오는 문제인데 쿼리 날려봤더니 401이라고 나옵니다. 혹시 back단에서 따로 graphql 에 대해 인증로직 추가했나요?

![image](https://user-images.githubusercontent.com/22424891/125428364-0d06af75-258f-45e6-b039-a22cdf077746.png)

![image](https://user-images.githubusercontent.com/22424891/125428286-8214f6ec-5df1-427e-8b7e-16ea82dbf46c.png)

**Comment by hochan222** [comment]
아 여기군요

![image](https://user-images.githubusercontent.com/22424891/125429091-9d433de9-0c4a-439e-9052-e475f2321332.png)

**Comment by yechoi42** [comment]
`user.resolver.ts`에 GqlAuthGuard 적용돼있어요!

**Comment by hochan222** [comment]
## cors 문제 발생

1. graphql playground에서 적정 authorization  헤더를 넣은뒤 보내면 응답이 잘온다.

  <img src="https://user-images.githubusercontent.com/22424891/125570936-32810e0f-0c72-4e09-b759-624ef43f2145.png" height="300px" />

2. react 쪽에서도 apollo client 설정할때 헤더에 authorization을 설정해준다.

  <img src="https://user-images.githubusercontent.com/22424891/125571083-f663d420-c58c-4b71-8cfc-4c3e1b79dd60.png" height="300px" />

3. 이는 nestjs에서 결국 GqlAuthGuard 를 거치게 되는데 ctx.getContext().req.cookies 에 설정한 내용이 담겨온다.

  <img src="https://user-images.githubusercontent.com/22424891/125571083-f663d420-c58c-4b71-8cfc-4c3e1b79dd60.png" height="300px" />
![image](https://user-images.githubusercontent.com/22424891/125571200-1f59acc8-923f-4f55-abf5-93f26d6ea0ac.png)

**Comment by hochan222** [comment]
## [[Typescript] CRA에서 http-proxy-middleware 사용법](https://egas.tistory.com/39)

후.. typescript는 지원하지 않았다니 충격이다. 어쨌든 Proxy 설정 완료.

**Comment by hochan222** [comment]
## 인증된 사용자 정보 프런트에서 불러오기

@yechoi42 님께서 이미 틀을 다 만들어주셔서 편했습니다. 


<img src="https://user-images.githubusercontent.com/22424891/125619119-acb76357-e167-44be-bffa-8df5ed57fe2b.png" height="150px" />

<img src="https://user-images.githubusercontent.com/22424891/125619161-ec3ea433-dbc2-47ef-a3bf-fef1319ce7fd.png" height="150px" />
