### ISSUE TITLE
[Figma] 프론트 디자인

### ISSUE THREAD

**Issue by jwon42** [transcendence42/ft_transcendence#57]
우리가 계획했던 건 로그인 페이지 제외하고는 거의 다 된 것 같아요.
세부적인 디자인들 각 페이지마다 필요한 요소(알림창 등)들이 있다면 댓글로 제안해주시거나 직접 수정해주세요.

----

1. Navigation, Sidebar

<img height="500" src="https://user-images.githubusercontent.com/61400214/123955071-2a470380-d9e4-11eb-963b-0ec7a05efd37.png">

2. Main Page

<img height="500" src="https://user-images.githubusercontent.com/61400214/123955150-421e8780-d9e4-11eb-822b-4a4222dea561.png">

3. Game Page

<img height="500" src="https://user-images.githubusercontent.com/61400214/123955196-4ea2e000-d9e4-11eb-8959-ee6b0f583c9e.png">

4. Profile Page

<img height="500" src="https://user-images.githubusercontent.com/61400214/123955219-55c9ee00-d9e4-11eb-9fb6-c28d46a479a9.png">

5. Chat Page

<img height="500" src="https://user-images.githubusercontent.com/61400214/123955235-5a8ea200-d9e4-11eb-9f50-efba270cf2b1.png">

**Comment by hochan222** [comment]
전체적인 색상은 지금과 동일하게 가져가나요?
