### ISSUE TITLE
[docker-compose] 기본 환경 설정

### ISSUE THREAD

**Issue by hochan222** [transcendence42/ft_transcendence#6]
- [x] react 배포를 서버에서 할것인지 따로 서버를 만들것인지 결정
  - [x] react build 후 index 페이지 띄우기 / 서버 따로 띄우기
  - [x] PM2 등의 툴들 사용 여부
- [x] docker compose 기본 setting
- [x] dockerfile 작성
- [x] 설명 자료

**Comment by yechoi42** [comment]
## react-express 연동
express에서 react의 정적파일을 참고하는 방식으로 택하겠습니다.
proxy 설정, CORS 해결 등의 과정(그닥 어렵진 않지만..)을 거치지 않아도 돼서 더 간단하다고 판단했습니다.

-----

### react-express 연동 방식 
디렉토리 구조는 다음과 같다고 가정합니다.

```jsx
project
|-- client/
|
|__ server/
```

1. react에서 build한 정적파일을 express에서 사용하기
    - Express의 기본 제공 미들웨어 함수인 express.static을 사용

        ```jsx
        // server/index.js

        // react의 정적파일 제공하기
        app.use(express.static(path.join(__dirname, 'client/build')));
        // 라우트 설정하기
        app.get('*', (req, res) => {
          res.sendFile(path.join(__dirname+'/client/build/index.html'));
        });
        ```

    [🔗 docs](https://expressjs.com/ko/starter/static-files.html)

2. react와 express를 proxy로 연결하기

    ```jsx
    // http-proxy-middleware 설치
    npm install http-proxy-middleware
    ```

```jsx
// client/setProxy.js

// proxy 설정을 위한 js 파일 생성ㅇ
const proxy = require('http-proxy-middleware');

module.exports = (app) => {
	app.use(
		proxy('/', {
			target: 'http://localhost:5500/' //server의 포트
		})
	)
}
```

client와 server가 서로 다른 포트를 사용하고 있기 때문에, CORS 정책을 위반하는 문제가 생긴다. 이를 해결하기 위해 cors 모듈을 추가적으로 설치하고 cors를 삽입한다.

[🔗블로그](https://junho0956.tistory.com/328)

**Comment by yechoi42** [comment]
### 📋 docker-compose 설명자료

https://www.notion.so/docker-compose-61729d6269174dffa7468375ab2db904
