### ISSUE TITLE
[NestJS] admin view

### ISSUE THREAD

**Issue by yechoi42** [transcendence42/ft_transcendence#89]
- There will be an **admin view**, chat with moderators, real-time multiplayer online games.
- nestjs-admin  https://nestjs-admin.com/docs/install
- 어드민브로 https://adminbro.com/module-@admin-bro_nestjs.html

**Comment by yhshin0** [comment]
admin-bro 구성 @jwon42

**Comment by yechoi42** [comment]
admin-bro 버그가 많아서 nestjs admin으로 갈아탐 

설치 문서: https://nestjs-admin.com/docs/install

**Comment by yechoi42** [comment]
![image](https://user-images.githubusercontent.com/61399588/126321586-4922b0f7-5fe2-4d0f-a994-7bb1053ef00b.png)

계속 이런 이슈있었는데 nestjs-admin 자체의 버그가 있어서 그렇습니다.
https://github.com/Theodo-UK/nestjs-admin/issues/213 이 이슈고요.
공식적인 버그 픽스는 안된 상태이고, 대신 코멘트 중에 돌아가게 만드는 방법이 있습니다.
https://github.com/Theodo-UK/nestjs-admin/issues/213#issuecomment-798956737 이 코멘트인데요.
정리하자면

1. `npx nestjs-admin createAdminUser`로 adminUser 생성
2. https://bcrypt-generator.com/ 여기서 원하는 비밀번호를 암호화한다
3. DB에 들어가서 adminUser에 암호화한 비밀번호를 직접 넣어준다.
```
update "adminUser" set password = '직접 해쉬한 비밀번호' where username = '1에서 생성한 adminUser의 username';
```

**Comment by yechoi42** [comment]
![스크린샷 2021-07-21 오전 12 45 53](https://user-images.githubusercontent.com/61399588/126468721-a7cb89e4-b046-4bf7-b4b0-6c7101bde764.png)
 
어제는 잘 됐지만, 올바른 비밀번호를 입력해도 `/admin`에서 계속해서 `/admin/login`으로 리다이렉트 되는 문제가 계속됐습니다.

### AdminBro 설치
AdminBro 설치를 다시 시도해봤습니다.
type 중복으로 인한 에러 때문에 `tsconfig.json`에서 `"skipLibCheck": true,`  설정해줘야 합니다.
전반적인 설치 과정은 [이 블로그](https://itnext.io/setup-adminbro-for-nestjs-application-de5bc12bc3b3)를 참고했습니다. 
![스크린샷 2021-07-21 오후 6 42 23](https://user-images.githubusercontent.com/61399588/126469098-a96c8f9f-0596-4366-b3a2-7e064fd24ff7.png)

**Comment by jwon42** [comment]
adminbro 접근용 관리자계정 생성했습니다.

접근 url: http://localhost:5500/admin
이메일: admin@admin.com
비밀번호: admin

현재는 adminUserInfo라는 객체를 생성하여 
그 안에 관리자 정보를 담고 있으며 코드에 노출되어 있고 암호화 또한 되어있지 않습니다.

추후 두가지 중 하나의 리팩토링이 필요합니다.
1. User Entity에 isAdmin(boolean) 칼럼을 추가하여 접근 가능하도록 리팩토링
2. 환경변수에 이메일과 비밀번호를 미리 정의
