### ISSUE TITLE
[TypeOrm] 친구 관계 설정

### ISSUE THREAD

**Issue by jwon42** [transcendence42/ft_transcendence#95]
기존 User entity에서 friendID, blockID가 자기 자신을 참조하도록 변경이 필요합니다.]
---> 은 follow 테이블을 만들어서 self-reference 하지 않습니다

참고할 글
https://github.com/typeorm/typeorm/blob/master/docs/relations-faq.md
https://github.com/typeorm/typeorm/blob/master/docs/tree-entities.md

**Comment by hochan222** [comment]
## tree 구조로 친구 관계를 형성하면 안되는 이유

yechoi는 holee 부모 노드 하나만 있을 수 밖에 없다. (더군다나 자식에도 holee가 있으면...) 친구는 tree 구조가 아닌 그물 구조가 되야한다. 

```
               holee
               /  \
          yechoi  jwon
          /   \
      holee  yshin
```

## Entity (Many to Many)

우리는 @ManyToMany(type => User) 로 그물 구조를 만들 수 있다.

```
  @ManyToMany(type => User)
  @JoinTable()
  friends: User[];
```

## query

... 부르고 저장하는법 찾는중

**Comment by yechoi42** [comment]
## 참고
- [typeORM relations](https://github.com/typeorm/typeorm/blob/master/docs/relations.md)

**Comment by yechoi42** [comment]
### 현재 상황과 해결방법
![image](https://user-images.githubusercontent.com/61399588/125571225-8293f84a-06cb-4ae0-8e31-75235f9debfd.png)

createFollow 하면 user 정보가 저장이 안됨. followingIndex, followerIndext라는 열이 생기는데...

**Comment by yechoi42** [comment]
## 리졸버 붙여서 user에서 followings, followers 정보 가지고 오기

리졸버는 특정 필드의 데이터를 반환하는, 실제 데이터를 가지고 오는 일을 하는 함수입니다. 스키마에 정의된 타입과 형태에 따라 데이터를 반환합니다. 

nestjs에서는 데코레이터를 활용해 리졸버를 만듭니다. 👉 [문서](https://docs.nestjs.kr/graphql/resolvers)
모든 데코레이터 (예: @ Resolver, @ ResolveField, @ Args 등)는 @nestjs/graphql 패키지에서 내보내집니다.
리졸버 클래스를 정의하면 nest는 런타임에 결합합니다. 

resolver를 만들려면 UsersService에서 FollowsService를 참조해야 하는데요, 이미 FollowsService에서 UsersService를 사용하고 있기 때문에 순환참조 문제가 발생합니다. 이 [문서](https://docs.nestjs.kr/fundamentals/circular-dependency)와 이 [블로그](https://velog.io/@peter0618/NestJs-circular-dependency-%EB%AC%B8%EC%A0%9C-%ED%95%B4%EA%B2%B0)를 참고해 forwardRef로 순환참조 문제를 해결해줬습니다. 

그럼 정말 리졸버를 만들 시간!

**Comment by hochan222** [comment]
alarm과 user를 순환참조 설정을하는데 user의 경우는 auth와도 관련있어서 auth 도 설정 해주니 됐습니다.

**Comment by yechoi42** [comment]
#11 에 자세한 스펙이 있지만, 자주 사용할 것 같은 기능들을 좀더 풀어서 정리해보았습니다. 
![image](https://user-images.githubusercontent.com/61399588/125911686-08357d5f-d67b-494a-aa43-9283c4747ba2.png)
(_그림으로 표현하려고 했으나... 손이 많이 가서 한장 그리고 말았읍니다..._ )

- 친구 신청: `createFollow`(mutation)
 - 상대방이 맞신청을 할 경우, 두 Follow 정보에서 checked가 true가 됩니다. 
 - 예) A(follower)->B(following) Follow 정보에서 checked === false 인 상태,
   이후 B(follower)->A(following)가 follow 하면, B->A Follow의 checked === true이고 A->B follow의 checked === true 로 변경

- 블록 / 블록 해제: `toggleBlock'(mutation)
  - 블록하려는 주체가 follower, 블록 당하는 주체가 following인 Follow 데이터를 찾습니다 
  - 해당 데이터의 blocked를 toggle 합니다.
  - 예) A가 B를 블록하려면 A(follower)-> B(following) Follow 정보에서 blocked가 디폴트값인 false에서 true로 toggle됨
  - 만약 block하고 싶은 유저가 기본에 follow하고 있던 유저가 아니면, A(follower)->B(following) Follow 정보를 새로 생성하고 blocked === true 로 설정합니다. 

- 친구 찾기: `friends`(query)
  - follwer가 주어진 userID인 사람 중, checked === true(맞팔돼있고), blocked === false 사람을 찾습니다.
  - 그러니까 맞팔한 사람 중 블록 안된 사람이 친구입니다.

- 블록된 유저 찾기: `blockedUsers`(query(
  - follower가 주어진 userID인 사람 중, blocked === true 인 사람을 찾습니다.
